package claude_test

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/lyarwood/cctv/internal/claude"
)

var _ = Describe("SanitizePrompt", func() {
	It("returns empty string for empty input", func() {
		Expect(claude.SanitizePrompt("")).To(Equal(""))
	})

	It("passes through plain text unchanged", func() {
		Expect(claude.SanitizePrompt("can you fix the login bug?")).To(Equal("can you fix the login bug?"))
	})

	It("extracts command name from command-message tags", func() {
		raw := `<command-message>kubevirt:review-pr</command-message>
<command-name>/kubevirt:review-pr</command-name>`
		Expect(claude.SanitizePrompt(raw)).To(Equal("/kubevirt:review-pr"))
	})

	It("extracts command name and args", func() {
		raw := `<command-message>kubevirt:review-pr</command-message>
<command-name>/kubevirt:review-pr</command-name>
<command-args>https://github.com/kubevirt/enhancements/pull/272</command-args>`
		result := claude.SanitizePrompt(raw)
		Expect(result).To(HavePrefix("/kubevirt:review-pr"))
		Expect(result).To(ContainSubstring("272"))
	})

	It("returns [local command] for local-command-caveat with no real content", func() {
		raw := `<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>`
		Expect(claude.SanitizePrompt(raw)).To(Equal("[local command]"))
	})

	It("extracts content after local-command-caveat if present", func() {
		raw := `<local-command-caveat>Caveat: ignore this</local-command-caveat> actual user question here`
		Expect(claude.SanitizePrompt(raw)).To(Equal("actual user question here"))
	})

	It("extracts bash-input commands", func() {
		raw := `<bash-input>gh pr checkout 1665</bash-input>`
		Expect(claude.SanitizePrompt(raw)).To(Equal("$ gh pr checkout 1665"))
	})

	It("strips XML tags from mixed content", func() {
		raw := `<some-tag>hidden</some-tag> visible text <other>more hidden</other>`
		Expect(claude.SanitizePrompt(raw)).To(Equal("hidden visible text more hidden"))
	})

	It("shortens long URLs", func() {
		raw := "check https://github.com/kubevirt/enhancements/pull/272 please"
		result := claude.SanitizePrompt(raw)
		Expect(result).To(ContainSubstring("github.com"))
		Expect(result).To(ContainSubstring("272"))
		Expect(result).NotTo(ContainSubstring("https://"))
	})

	It("normalizes whitespace", func() {
		raw := "can  you   fix\n\nthe   bug"
		Expect(claude.SanitizePrompt(raw)).To(Equal("can you fix the bug"))
	})
})
